const GET_SYNONYMS = 'GET_SYNONYMS'
const GET_SYNONYMS_ASYNC = 'GET_SYNONYMS_ASYNC'

const SET_TYPE_OF_EDITING = 'SET_TYPE_OF_EDITING'

export { GET_SYNONYMS, GET_SYNONYMS_ASYNC, SET_TYPE_OF_EDITING }
